fail_fast: true
repos:
- repo: local
  hooks:

    - id: pyink
      name: pyink
      entry: poetry run pyink
      language: system
      types: [file, python]
      files: '^smart_control/'

    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [file, python]
      files: '^smart_control/'
      exclude: '^smart_control/proto/'

    # NOTE: running `pylint` against all files is prohibitively slow
    # ... so we omit passing the `smart_buildings` directory,
    # ... which allows pre-commit to run against staged / changed files only
    - id: pylint
      name: pylint
      #entry: pylint --rcfile=.pylintrc --ignore=proto smart_control
      #entry: pylint --rcfile=.pylintrc --ignore=proto $(git diff --name-only --staged | grep -E '\.py$')
      entry: pylint --rcfile=.pylintrc --ignore=proto
      language: system
      types: [file, python]
      files: '^smart_control/'
      exclude: '^smart_control/proto/'

# See: https://mdformat.readthedocs.io/en/stable/users/installation_and_usage.html#usage-as-a-pre-commit-hook
- repo: https://github.com/hukkin/mdformat
  rev: 0.7.22
  hooks:
  - id: mdformat
    exclude: ^docs/api/
