classDiagram
    direction LR
  class ActionConfig {
  }
  class ActionNormalizerTest {
  }
  class AgentUtilsTest {
  }
  class AirHandler {
  }
  class AirHandlerTest {
  }
  class AttributeInfo {
  }
  class BadObservationBuilding {
  }
  class BadSetpointSchedule {
  }
  class BaseActionNormalizer {
  }
  class BaseBuilding {
  }
  class BaseConvectionSimulator {
  }
  class BaseEnergyCost {
  }
  class BaseLearningAlgorithm {
  }
  class BaseObservationNormalizer {
  }
  class BaseOccupancy {
  }
  class BaseReader {
  }
  class BaseReducedSequence {
  }
  class BaseReducer {
  }
  class BaseRewardFunction {
  }
  class BaseRunCommandPredictor {
  }
  class BaseSetpointEnergyCarbonRewardFunction {
  }
  class BaseSetpointEnergyCarbonRewardTest {
  }
  class BaseSimulatorBuilding {
  }
  class BaseWeatherController {
  }
  class BaseWriter {
  }
  class BaseWriterFactory {
  }
  class Boiler {
  }
  class BoilerTest {
  }
  class BoundedActionNormalizer {
  }
  class Building {
  }
  class BuildingDataset {
  }
  class BuildingDatasetPartition {
  }
  class BuildingImageGenerator {
  }
  class BuildingInfo {
  }
  class BuildingInfoTest {
  }
  class BuildingRadiationScriptFTest {
  }
  class BuildingRadiationUtilsTest {
  }
  class BuildingRenderer {
  }
  class BuildingTest {
  }
  class BuildingUtilsTest {
  }
  class CVBoundaryType {
  }
  class CVCornerOrientationType {
  }
  class CVEdgeOrientationType {
  }
  class CVPositionType {
  }
  class CVType {
  }
  class CompositeObserver {
  }
  class ControllerReadWriteTest {
  }
  class ConversionUtilsTest {
  }
  class DefaultExteriorWallMaterialProperties {
  }
  class DefaultExteriorWallRadiationProperties {
  }
  class DefaultInsideAirMaterialProperties {
  }
  class DefaultInsideAirRadiationProperties {
  }
  class DefaultInsideWallMaterialProperties {
  }
  class DefaultInsideWallRadiationProperties {
  }
  class DeviceType {
  }
  class ElectricityEnergyCost {
  }
  class ElectricityEnergyCostTest {
  }
  class EnergyUtilsTest {
  }
  class EnhancedOccupancy {
  }
  class EnhancedOccupancyTest {
  }
  class Environment {
  }
  class EnvironmentTest {
  }
  class ExteriorRadiationData {
  }
  class FlexibleFloorplanSimulatorTest {
  }
  class FloorPlanBasedBuilding {
  }
  class FloorPlanBasedHvac {
  }
  class FloorPlanBasedHvacTest {
  }
  class GetObservationValueTest {
  }
  class GetReplayCloudCoverTest {
  }
  class GetReplayIrradianceTest {
  }
  class GetReplaySkyTemperatureTest {
  }
  class GetReplayTemperaturesTest {
  }
  class Heater {
  }
  class HistogramReducedSequence {
  }
  class HistogramReducer {
  }
  class HistogramReducerTest {
  }
  class Hvac {
  }
  class HvacTest {
  }
  class IdentityReducedSequence {
  }
  class IdentityReducer {
  }
  class IrradianceComponents {
  }
  class IrradianceComponentsTest {
  }
  class IrradianceDecompositionPvlibValidationTest {
  }
  class IrradianceTestBase {
  }
  class LIGHTSWITCHOccupancy {
  }
  class LIGHTSWITCHOccupancyTest {
  }
  class MaterialProperties {
  }
  class MinuteLevelZoneOccupant {
  }
  class Mode {
  }
  class MoffettReplayWeatherControllerTest {
  }
  class NaturalGasEnergyCost {
  }
  class NaturalGasEnergyCostTest {
  }
  class ObservationNormalizerTest {
  }
  class Observer {
  }
  class OccupancyStateEnum {
  }
  class OccupancyStateEnum {
  }
  class OccupancyStateEnum {
  }
  class PrintStatusObserver {
  }
  class ProtoReader {
  }
  class ProtoWriter {
  }
  class ProtoWriterFactory {
  }
  class RadiationProperties {
  }
  class RadiationPropertiesTest {
  }
  class RandomForestLearningAlgorithm {
  }
  class RandomizedArrivalDepartureOccupancy {
  }
  class RandomizedArrivalDepartureOccupancyTest {
  }
  class Readers {
  }
  class RealBuildingTemperatureArrayGenerator {
  }
  class ReducerTest {
  }
  class RegressionBuildingUtilsTest {
  }
  class RejectionBuilding {
  }
  class RejectionSimulatorBuilding {
  }
  class RejectionSimulatorBuildingTest {
  }
  class RenderingObserver {
  }
  class ReplayBufferManager {
  }
  class ReplaySolarRadiationTest {
  }
  class ReplayWeatherController {
  }
  class ReplayWeatherControllerTest {
  }
  class ReverbInstallationTest {
  }
  class RunCommandPredictor {
  }
  class RunCommandPredictorTest {
  }
  class ScheduleEvent {
  }
  class SchedulePolicy {
  }
  class SetpointEnergyCarbonRegretFunction {
  }
  class SetpointEnergyCarbonRegretTest {
  }
  class SetpointEnergyCarbonRewardFunction {
  }
  class SetpointEnergyCarbonRewardTest {
  }
  class SetpointSchedule {
  }
  class SetpointScheduleTest {
  }
  class SimpleBuilding {
  }
  class SimpleRewardFunction {
  }
  class Simulator {
  }
  class SimulatorBuilding {
  }
  class SimulatorBuildingTest {
  }
  class SimulatorBuildingTestBase {
  }
  class SimulatorFlexibleGeometries {
  }
  class SimulatorTest {
  }
  class SmartDevice {
  }
  class SmartDeviceTest {
  }
  class SolarRadiation {
  }
  class SolarRadiationPvlibValidationTest {
  }
  class SolarRadiationTest {
  }
  class StandardScoreObservationNormalizer {
  }
  class StatsReducedSequence {
  }
  class StatsReducer {
  }
  class StatusRejectionBuilding {
  }
  class StepFunctionOccupancy {
  }
  class StepFunctionOccupancyModelTest {
  }
  class StochasticConvectionSimulator {
  }
  class TFSimulator {
  }
  class TFSimulatorTest {
  }
  class TerminatingEnv {
  }
  class TestAllBuildingDatasetPartitions {
  }
  class TestBuildingDataset {
  }
  class TestBuildingDatasetPartition {
  }
  class TestConfigPaths {
  }
  class TestDataDirectory {
  }
  class TestEnergyCost {
  }
  class TestEnergyCost {
  }
  class TestEnergyCost {
  }
  class TestOccupancy {
  }
  class TestReader {
  }
  class TestReader {
  }
  class TestReader {
  }
  class TestTempConversions {
  }
  class ThermalDiffuserUtilsTest {
  }
  class Thermostat {
  }
  class ThermostatTest {
  }
  class TimeIntervalEnum {
  }
  class Vav {
  }
  class VavTest {
  }
  class VisualLogger {
  }
  class WeatherController {
  }
  class WeatherControllerTest {
  }
  class WorkerType {
  }
  class ZoneOccupant {
  }
  class ZoneOccupant {
  }
  class _TanhNormalProjectionNetworkWrapper {
  }
  RejectionBuilding --|> SimpleBuilding
  StatusRejectionBuilding --|> SimpleBuilding
  BadObservationBuilding --|> SimpleBuilding
  TerminatingEnv --|> Environment
  SimpleBuilding --|> BaseBuilding
  SimpleRewardFunction --|> BaseRewardFunction
  CompositeObserver --|> Observer
  PrintStatusObserver --|> Observer
  RenderingObserver --|> Observer
  BaseSetpointEnergyCarbonRewardFunction --|> BaseRewardFunction
  TestEnergyCost --|> BaseEnergyCost
  ElectricityEnergyCost --|> BaseEnergyCost
  NaturalGasEnergyCost --|> BaseEnergyCost
  SetpointEnergyCarbonRegretFunction --|> BaseSetpointEnergyCarbonRewardFunction
  TestEnergyCost --|> BaseEnergyCost
  SetpointEnergyCarbonRewardFunction --|> BaseSetpointEnergyCarbonRewardFunction
  TestEnergyCost --|> BaseEnergyCost
  AirHandler --|> SmartDevice
  Boiler --|> SmartDevice
  Building --|> BaseSimulatorBuilding
  DefaultExteriorWallMaterialProperties --|> MaterialProperties
  DefaultExteriorWallRadiationProperties --|> RadiationProperties
  DefaultInsideAirMaterialProperties --|> MaterialProperties
  DefaultInsideAirRadiationProperties --|> RadiationProperties
  DefaultInsideWallMaterialProperties --|> MaterialProperties
  DefaultInsideWallRadiationProperties --|> RadiationProperties
  FloorPlanBasedBuilding --|> BaseSimulatorBuilding
  EnhancedOccupancy --|> BaseOccupancy
  RandomizedArrivalDepartureOccupancy --|> BaseOccupancy
  RejectionSimulatorBuilding --|> BaseBuilding
  RejectionSimulatorBuildingTest --|> SimulatorBuildingTestBase
  SimulatorBuilding --|> BaseBuilding
  SimulatorBuildingTest --|> SimulatorBuildingTestBase
  SimulatorFlexibleGeometries --|> Simulator
  Heater --|> SmartDevice
  ReplaySolarRadiationTest --|> SolarRadiationTest
  SolarRadiationPvlibValidationTest --|> IrradianceTestBase
  SolarRadiationTest --|> IrradianceTestBase
  StepFunctionOccupancy --|> BaseOccupancy
  StochasticConvectionSimulator --|> BaseConvectionSimulator
  LIGHTSWITCHOccupancy --|> BaseOccupancy
  TFSimulator --|> SimulatorFlexibleGeometries
  Vav --|> SmartDevice
  ReplayWeatherController --|> BaseWeatherController
  WeatherController --|> BaseWeatherController
  BoundedActionNormalizer --|> BaseActionNormalizer
  ProtoReader --|> BaseReader
  ProtoWriter --|> BaseWriter
  ProtoWriterFactory --|> BaseWriterFactory
  HistogramReducer --|> BaseReducer
  HistogramReducedSequence --|> BaseReducedSequence
  TestReader --|> BaseReader
  StandardScoreObservationNormalizer --|> BaseObservationNormalizer
  IdentityReducer --|> BaseReducer
  IdentityReducedSequence --|> BaseReducedSequence
  StatsReducer --|> BaseReducer
  StatsReducedSequence --|> BaseReducedSequence
  TestOccupancy --|> BaseOccupancy
  BadSetpointSchedule --|> SetpointSchedule
  RandomForestLearningAlgorithm --|> BaseLearningAlgorithm
  RunCommandPredictor --|> BaseRunCommandPredictor
  TestReader --|> BaseReader
  TestReader --|> BaseReader
  DeviceType --* ScheduleEvent : device
  AirHandler --* FloorPlanBasedHvacTest : _global_handler
  Boiler --* FloorPlanBasedHvacTest : _global_boiler
  FloorPlanBasedBuilding --* BuildingRadiationScriptFTest : building
  FloorPlanBasedBuilding --* BuildingRadiationScriptFTest : building_with_interior_mass
  FloorPlanBasedHvac --* FloorPlanBasedHvacTest : _hvac
  SetpointSchedule --* FloorPlanBasedHvacTest : _global_setpoint_schedule
  BuildingInfo --* SolarRadiation : building_info
  BuildingInfo --* ReplaySolarRadiationTest : building_info
  BuildingInfo --* SolarRadiationTest : building_info
  IrradianceComponents --* ExteriorRadiationData : irradiance
  SolarRadiation --* ReplaySolarRadiationTest : solar_radiation
  SolarRadiation --* SolarRadiationTest : solar_radiation
  StepFunctionOccupancy --* SimulatorBuildingTestBase : occupancy
  StochasticConvectionSimulator --* FloorPlanBasedBuilding : _convection_simulator
  StochasticConvectionSimulator --* FloorPlanBasedBuilding : _convection_simulator
  ReplayWeatherController --* ReplaySolarRadiationTest : weather_controller
  ReplayWeatherController --* MoffettReplayWeatherControllerTest : controller
  ReplayWeatherController --* ReplayWeatherControllerTest : controller
  WeatherController --* SolarRadiationTest : weather_controller
  VisualLogger --* SimulatorFlexibleGeometries : _log_and_plotter
  BuildingDataset --o BuildingDatasetPartition : ds
  BaseBuilding --o Environment : building
  BaseBuilding --o RejectionSimulatorBuilding : _base_building
  BaseEnergyCost --o SetpointEnergyCarbonRegretFunction : _electricity_energy_cost
  BaseEnergyCost --o SetpointEnergyCarbonRegretFunction : _natural_gas_energy_cost
  BaseEnergyCost --o SetpointEnergyCarbonRewardFunction : _electricity_energy_cost
  BaseEnergyCost --o SetpointEnergyCarbonRewardFunction : _natural_gas_energy_cost
  BaseObservationNormalizer --o Environment : _observation_normalizer
  BaseOccupancy --o SimulatorBuilding : _occupancy
  BaseRewardFunction --o Environment : reward_function
  AirHandler --o Hvac : _air_handler
  AirHandler --o FloorPlanBasedHvac : _air_handler
  Boiler --o Hvac : _boiler
  Boiler --o FloorPlanBasedHvac : _boiler
  Boiler --o Vav : _boiler
  Building --o Simulator : building
  FloorPlanBasedBuilding --o SimulatorFlexibleGeometries : building
  WorkerType --o MinuteLevelZoneOccupant : worker_type
  Hvac --o Simulator : _hvac
  FloorPlanBasedHvac --o SimulatorFlexibleGeometries : _hvac
  SetpointSchedule --o Hvac : _schedule
  SetpointSchedule --o FloorPlanBasedHvac : _schedule
  SetpointSchedule --o Thermostat : _setpoint_schedule
  Heater --o SmartDeviceTest : heater_class
  CVPositionType --o CVType : position
  Thermostat --o Vav : _init_thermostat
  WeatherController --o Simulator : _weather_controller
  BuildingRenderer --o VisualLogger : _renderer
  BaseLearningAlgorithm --o RunCommandPredictor : _learning_algo
