# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart_control_normalization.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='smart_control_normalization.proto',
  package='smart_buildings.smart_control.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!smart_control_normalization.proto\x12#smart_buildings.smart_control.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x02\n\x16\x43ontinuousVariableInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x30\n\x0csample_start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nsample_end\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bsample_size\x18\x04 \x01(\x05\x12\x17\n\x0fsample_variance\x18\x05 \x01(\x02\x12\x13\n\x0bsample_mean\x18\x06 \x01(\x02\x12\x15\n\rsample_median\x18\x07 \x01(\x02\x12\x16\n\x0esample_maximum\x18\x08 \x01(\x02\x12\x16\n\x0esample_minimum\x18\t \x01(\x02\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CONTINUOUSVARIABLEINFO = _descriptor.Descriptor(
  name='ContinuousVariableInfo',
  full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_start', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.sample_start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_end', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.sample_end', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_size', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.sample_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_variance', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.sample_variance', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_mean', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.sample_mean', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_median', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.sample_median', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_maximum', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.sample_maximum', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_minimum', full_name='smart_buildings.smart_control.proto.ContinuousVariableInfo.sample_minimum', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=380,
)

_CONTINUOUSVARIABLEINFO.fields_by_name['sample_start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CONTINUOUSVARIABLEINFO.fields_by_name['sample_end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ContinuousVariableInfo'] = _CONTINUOUSVARIABLEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContinuousVariableInfo = _reflection.GeneratedProtocolMessageType('ContinuousVariableInfo', (_message.Message,), {
  'DESCRIPTOR' : _CONTINUOUSVARIABLEINFO,
  '__module__' : 'smart_control_normalization_pb2'
  # @@protoc_insertion_point(class_scope:smart_buildings.smart_control.proto.ContinuousVariableInfo)
  })
_sym_db.RegisterMessage(ContinuousVariableInfo)


# @@protoc_insertion_point(module_scope)
