"""Test helpers for configs tests."""

# WEATHER DATA

WEATHER_COLUMNS = [
    "Time",
    "StationName",
    "Location",
    "TempC",
    "DewPointC",
    "BarometerMbar",
    "Rain",
    "RainTotal",
    "WindspeedKmph",
    "WindDirection",
    "SkyCoverage",
    "VisibilityKm",
    "Humidity",
    "TempF",
    "HumidityARM",
]

# ENVIRONMENT

ACTION_NORMALIZER_NAMES = [
    "ahu_1_supply_air_temperature_setpoint",
    "ahu_1_static_pressure_setpoint",
    "ahu_2_supply_air_temperature_setpoint",
    "ahu_2_static_pressure_setpoint",
    "supply_water_setpoint",
    "differential_pressure",
]

ACTION_NAMES = [
    "ahs_ahu_1_supply_air_temperature_setpoint",
    "ahs_ahu_1_static_pressure_setpoint",
    "ahs_ahu_2_supply_air_temperature_setpoint",
    "ahs_ahu_2_static_pressure_setpoint",
    "hws_supply_water_setpoint",
    "hws_differential_pressure",
]

DEFAULT_ACTION_VALUES = [-0.2, 1.0, -0.2, 1.0, 0.5, 1.0]

ACTION_FIELDS = [
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "ahs_ahu_1_supply_air_temperature_setpoint",
        "setpoint_name": "ahu_1_supply_air_temperature_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 285.0,
        "max_native_value": 305.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "ahs_ahu_1_static_pressure_setpoint",
        "setpoint_name": "ahu_1_static_pressure_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 0.0,
        "max_native_value": 20000.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "ahs_ahu_2_supply_air_temperature_setpoint",
        "setpoint_name": "ahu_2_supply_air_temperature_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 285.0,
        "max_native_value": 305.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "ahs_ahu_2_static_pressure_setpoint",
        "setpoint_name": "ahu_2_static_pressure_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 0.0,
        "max_native_value": 20000.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "hws",
        "device_type": "HWS",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "hws_supply_water_setpoint",
        "setpoint_name": "supply_water_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 310.0,
        "max_native_value": 350.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "hws",
        "device_type": "HWS",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "hws_differential_pressure",
        "setpoint_name": "differential_pressure",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 0.0,
        "max_native_value": 20.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
]

# HYBRID ACTION ENVIRONMENT

HYBRID_ACTION_NAMES = [
    "ahs_ahu_1_supervisor_run_command",
    "ahs_ahu_2_supervisor_run_command",
    "ahs_ahu_1_supply_air_temperature_setpoint",
    "ahs_ahu_1_static_pressure_setpoint",
    "ahs_ahu_2_supply_air_temperature_setpoint",
    "ahs_ahu_2_static_pressure_setpoint",
    "hws_supervisor_run_command",
    "hws_supply_water_setpoint",
    "hws_differential_pressure",
]

HYBRID_ACTION_NORMALIZER_NAMES = [
    "supply_water_setpoint",
    "differential_pressure",
    "ahu_1_supply_air_temperature_setpoint",
    "ahu_1_static_pressure_setpoint",
    "ahu_2_supply_air_temperature_setpoint",
    "ahu_2_static_pressure_setpoint",
    "supervisor_run_command",
    "ahu_1_supervisor_run_command",
    "ahu_2_supervisor_run_command",
]

HYBRID_DEFAULT_ACTION_VALUES = [1.0, 1.0, -0.2, 1.0, -0.2, 1.0, 1.0, 0.5, 1.0]

HYBRID_ACTION_FIELDS = [
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "DISCRETE",
        "action_name": "ahs_ahu_1_supervisor_run_command",
        "setpoint_name": "ahu_1_supervisor_run_command",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 0.0,
        "max_native_value": 1.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "DISCRETE",
        "action_name": "ahs_ahu_2_supervisor_run_command",
        "setpoint_name": "ahu_2_supervisor_run_command",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 0.0,
        "max_native_value": 1.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "ahs_ahu_1_supply_air_temperature_setpoint",
        "setpoint_name": "ahu_1_supply_air_temperature_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 285.0,
        "max_native_value": 305.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "ahs_ahu_1_static_pressure_setpoint",
        "setpoint_name": "ahu_1_static_pressure_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 0.0,
        "max_native_value": 20000.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "ahs_ahu_2_supply_air_temperature_setpoint",
        "setpoint_name": "ahu_2_supply_air_temperature_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 285.0,
        "max_native_value": 305.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "ahs",
        "device_type": "AHU",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "ahs_ahu_2_static_pressure_setpoint",
        "setpoint_name": "ahu_2_static_pressure_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 0.0,
        "max_native_value": 20000.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "hws",
        "device_type": "HWS",
        "zone_id": "default_zone_id",
        "setpoint_type": "DISCRETE",
        "action_name": "hws_supervisor_run_command",
        "setpoint_name": "supervisor_run_command",
        "value_type": "VALUE_TYPE_UNDEFINED",
        "min_native_value": 0.0,
        "max_native_value": 1.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "hws",
        "device_type": "HWS",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "hws_supply_water_setpoint",
        "setpoint_name": "supply_water_setpoint",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 310.0,
        "max_native_value": 350.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
    {
        "device_id": "hws",
        "device_type": "HWS",
        "zone_id": "default_zone_id",
        "setpoint_type": "CONTINUOUS",
        "action_name": "hws_differential_pressure",
        "setpoint_name": "differential_pressure",
        "value_type": "VALUE_CONTINUOUS",
        "min_native_value": 0.0,
        "max_native_value": 20.0,
        "min_normalized_value": -1.0,
        "max_normalized_value": 1.0,
    },
]
