name: Python CI

on:
  push:
  pull_request:
    branches:
      - master
      - copybara_push

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job

    strategy:
      matrix:
        python-version: [3.10.12, 3.10.15, 3.11]  # Python versions to test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checks out the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}  # Use Python version from the matrix

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler ffmpeg  # Install both protobuf and ffmpeg in one step

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv .venv
        source .venv/bin/activate
        pip install poetry
        poetry install
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
